#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/tags.$$"' EXIT
git ls-files | ctags --tag-relative -Rf"$dir/tags.$$" --languages=-sql --exclude=node_modules --exclude='*\.min\.*'
mv "$dir/tags.$$" "$dir/tags"
